{{ config(materialized='table') }}

WITH CUSTOMERS AS (

    SELECT
        "ID" AS CUSTOMER_ID,
        "FIRST_NAME",
        "LAST_NAME"

    FROM RAW_DATA.CUSTOMERS

),

ORDERS AS (

    SELECT
        "ID" AS ORDER_ID,
        "USER_ID" AS CUSTOMER_ID,
        "ORDER_DATE",
        "STATUS"

    FROM RAW_DATA.ORDERS

),

CUSTOMER_ORDERS AS (

    SELECT
        CUSTOMER_ID,

        MIN("ORDER_DATE") AS FIRST_ORDER_DATE,
        MAX("ORDER_DATE") AS MOST_RECENT_ORDER_DATE,
        COUNT(ORDER_ID) AS NUMBER_OF_ORDERS

    FROM ORDERS

    GROUP BY 1

),

FINAL AS (

    SELECT
        CUSTOMERS.CUSTOMER_ID,
        CUSTOMERS."FIRST_NAME",
        CUSTOMERS."LAST_NAME",
        CUSTOMER_ORDERS.FIRST_ORDER_DATE,
        CUSTOMER_ORDERS.MOST_RECENT_ORDER_DATE,
        COALESCE(CUSTOMER_ORDERS.NUMBER_OF_ORDERS, 0) AS NUMBER_OF_ORDERS

    FROM CUSTOMERS

    LEFT JOIN CUSTOMER_ORDERS USING (CUSTOMER_ID)

)

SELECT * FROM FINAL